services:
  userservice:
    build:
      context: ./userservice
      dockerfile: Dockerfile
      target: ${TARGET:-production}
    env_file:
      - ./userservice/.env
    ports:
      - "1111:1111"
    depends_on:
      - db

  orderservice:
    build:
      context: ./orderservice
      dockerfile: Dockerfile
      target: ${TARGET:-production}
    env_file:
      - ./orderservice/.env
    ports:
      - "2222:2222"
    depends_on:
      - db

  deliveryservice:
    build:
      context: ./deliveryservice
      dockerfile: Dockerfile
      target: ${TARGET:-production}
    env_file:
      - ./deliveryservice/.env
    ports:
      - "3333:3333"
    depends_on:
      - db

  paymentservice:
    build:
      context: ./paymentservice
      dockerfile: Dockerfile
      target: ${TARGET:-production}
    env_file:
      - ./paymentservice/.env
    ports:
      - "4444:4444"
    depends_on:
      - db

  menuservice:
    build:
      context: ./menuservice
      dockerfile: Dockerfile
      target: ${TARGET:-production}
    env_file:
      - ./menuservice/.env
    ports:
      - "5555:5555"
    depends_on:
      - db

  notificationservice:
    build:
      context: ./notificationservice
      dockerfile: Dockerfile
      target: ${TARGET:-production}
    env_file:
      - ./notificationservice/.env
    ports:
      - "6666:6666"
    depends_on:
      - db

  reviewservice:
    build:
      context: ./reviewservice
      dockerfile: Dockerfile
      target: ${TARGET:-production}
    env_file:
      - ./reviewservice/.env
    ports:
      - "7777:7777"
    depends_on:
      - db

  restaurantservice:
    build:
      context: ./restaurantservice
      dockerfile: Dockerfile
      target: ${TARGET:-production}
    env_file:
      - ./restaurantservice/.env
    ports:
      - "8888:8888"
    depends_on:
      - db

  gatewayservice:
    build:
      context: ./gatewayservice
      dockerfile: Dockerfile
      target: ${TARGET:-production}
    env_file:
      - ./gatewayservice/.env
    ports:
      - "9999:9999"
    depends_on:
      - db

  # nginx:
  #   image: nginx:alpine
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "80:80"
  #   depends_on:
  # - userservice
  # - gatewayservice
  # - orderservice
  # - deliveryservice
  # - paymentservice
  # - menuservice
  # - notificationservice
  # - reviewservice
  # - restaurantservice

  nginx:
    build: "./nginx"
    ports:
      - "80:80"
    depends_on:
      - userservice
      - gatewayservice
      - orderservice
      - deliveryservice
      - paymentservice
      - menuservice
      - notificationservice
      - reviewservice
      - restaurantservice

  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./database/pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"
