version: "3"

services:
  UserService:
    build:
      context: .
      dockerfile: ./UserService/Dockerfile
      target: ${TARGET:-production}
    env_file:
      - ./UserService/.env
    ports:
      - "8081:8081"

  OrderService:
    build:
      context: .
      dockerfile: ./OrderService/Dockerfile
      target: ${TARGET:-production}
    env_file:
      - ./OrderService/.env
    ports:
      - "8082:8082"

  DeliveryService:
    build:
      context: .
      dockerfile: ./DeliveryService/Dockerfile
      target: ${TARGET:-production}
    env_file:
      - ./DeliveryService/.env
    ports:
      - "8083:8083"

  PaymentService:
    build:
      context: .
      dockerfile: ./PaymentService/Dockerfile
      target: ${TARGET:-production}
    env_file:
      - ./PaymentService/.env
    ports:
      - "8084:8084"

  MenuService:
    build:
      context: .
      dockerfile: ./MenuService/Dockerfile
      target: ${TARGET:-production}
    env_file:
      - ./MenuService/.env
    ports:
      - "8085:8085"

  NotificationService:
    build:
      context: .
      dockerfile: ./NotificationService/Dockerfile
      target: ${TARGET:-production}
    env_file:
      - ./NotificationService/.env
    ports:
      - "8086:8086"

  ReviewService:
    build:
      context: .
      dockerfile: ./ReviewService/Dockerfile
      target: ${TARGET:-production}
    env_file:
      - ./ReviewService/.env
    ports:
      - "8087:8087"

  RestaurantService:
    build:
      context: .
      dockerfile: ./RestaurantService/Dockerfile
      target: ${TARGET:-production}
    env_file:
      - ./RestaurantService/.env
    ports:
      - "8088:8088"

  GatewayService:
    build:
      context: .
      dockerfile: ./GatewayService/Dockerfile
      target: ${TARGET:-production}
    env_file:
      - ./GatewayService/.env
    ports:
      - "8089:8089"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - GatewayService
      - UserService
      - FoodService
      - OrderService
      - DeliveryService
      - PaymentService
      - MenuService
      - NotificationService
      - ReviewService
      - RestaurantService
      - Gateway

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: go_foodflow
    ports:
      - "5432:5432"
